### ISSUE TITLE
The object reference wasn't defined as an object instance.

### ISSUE THREAD

**Issue by Rosmaninho** [ChrisAnd1998/FalconX-Center-Taskbar#28]
System.NullReferenceException: A referência de objecto não foi definida como uma instância de um objecto.
   em FalconX3.FalconX.Form1_Load(Object sender, EventArgs e)
   em System.EventHandler.Invoke(Object sender, EventArgs e)
   em System.Windows.Forms.Form.OnLoad(EventArgs e)
   em System.Windows.Forms.Form.OnCreateControl()
   em System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   em System.Windows.Forms.Control.CreateControl()
   em System.Windows.Forms.Control.WmShowWindow(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   em System.Windows.Forms.Form.WmShowWindow(Message& m)
   em System.Windows.Forms.Form.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
________________#end of details report mentions this#__________________

Para activar a depuração just-in-time (JIT), o ficheiro .config para esta
aplicação ou computador (machine.config) tem de ter o
valor jitDebugging definido na secção system.windows.forms.
A aplicação também tem de ser compilada com a depuração
activada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando a depuração JIT está activada, qualquer excepção não processada
será enviada para o depurador JIT registado no computador
em vez de ser processada por esta caixa de diálogo.

Last version that worked in my system was the 21.09 version. I am not using the store version.

**Comment by ChrisAnd1998** [comment]
> To enable just-in-time debugging (JIT), the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> activated.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exceptions
> will be sent to the registered JIT debugger on the computer
> instead of being processed by this dialog box.

I think whats happening here is that FalconX couldn't find the handle of the taskbar.

What version of Windows are you on? 
What build?
x64 or x86/x32?

**Comment by Rosmaninho** [comment]
Windows 10 Home, latest update x64...

**Comment by carrsteven** [comment]
I am also getting this error.

Windows 10 Enterprise x64
Version 1903 (Build 18632.418)

**Comment by ChrisAnd1998** [comment]
Store version or just the normal version?

**Comment by carrsteven** [comment]
I tested both, same error for both versions.

**Comment by ChrisAnd1998** [comment]
And 1.1.8.0 is also the last version you can run? If yes, something is going on in the new animation library. I will take a look at what is going on.

**Comment by carrsteven** [comment]
I'm not sure, I cannot find a 1.1.8.0 download link. I just found this program from a news article that showed up in my feed yesterday.

**Comment by ChrisAnd1998** [comment]
This is where you can find them. https://chrisandriessen.nl/web/downloads/falconx/

**Comment by carrsteven** [comment]
Confirmed. 1.1.8.0 does work.

**Comment by ChrisAnd1998** [comment]
Thanks! Can you also try 1.1.9.0 (The animations overhaul update)

**Comment by carrsteven** [comment]
1.1.9.0 crashes and doesn't give me any error information. I will dig through some event logs.

**Comment by carrsteven** [comment]
These are the 2 event logs I have for the 1.1.9.0 executable.

```
Application: FalconX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at FalconX3.Form1..ctor()

Exception Info: System.InvalidOperationException
   at FalconX3.My.MyProject+MyForms.Create__Instance__[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   at FalconX3.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   at FalconX3.My.MyApplication.Main(System.String[])


Faulting application name: FalconX.exe, version: 1.1.9.0, time stamp: 0xd768fa9f
Faulting module name: KERNELBASE.dll, version: 10.0.18362.418, time stamp: 0x2b181c2c
Exception code: 0xe0434352
Fault offset: 0x00113572
Faulting process id: 0x4d84
Faulting application start time: 0x01d5837829ceb127
Faulting application path: C:\Program Files (x86)\FalconX\1.1.9.0\FalconX.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8c54bb7e-9ccb-4c0d-8b67-428138794f44
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by ChrisAnd1998** [comment]
Allright, the event log doesn't tell me whats going on exactly only that it fails when the first form got created.

I have been changing some stuff up and merged the VisualEffect libary right into FalconX. 
Here is the current testing build i just uploaded. Does it make a difference?
https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by carrsteven** [comment]
That build is also not working, throwing the same event logs as above.

**Comment by ChrisAnd1998** [comment]
I am still trying to fix this issue. The weird thing is that this error is very rare and i don't know why it happens.

> A NullReferenceException exception is thrown when you try to access a member on a type whose value is null

So what i did now is giving every Reference a default value so it can't be "NULL"
I hope this will fix it. If not i will continue trying.

_FalconX_TESTING_1.2.6.0_v2.zip_

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by ChrisAnd1998** [comment]
I also enabled every possible warnings in the project and fixed every warning that could lead to a NullReferenceException error according to the warning.

_FalconX_TESTING_1.2.6.0_v3.zip_

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by ChrisAnd1998** [comment]
Someone else has confirmed that it's fixed now. So i am going to close this issue for now.

**Comment by carrsteven** [comment]
Still crashes for me with the same errors on my end. Sorry for not getting back to you sooner. No worries though, I will continue to use the old version that does work.

**Comment by ChrisAnd1998** [comment]
Thanks for letting me know, i really don't know what could fix this issue anymore. I have been trying and trying as I can't reproduce this bug on my own pc and others. I hope to find a fix in the future.

**Comment by Rosmaninho** [comment]
The 1.2.8.0 version is working for me!!! And I finally have the centered toolbar in my secondary monitor! woohoo!!!

**Comment by ChrisAnd1998** [comment]
Very nice! 😁😁😁

**Comment by carrsteven** [comment]
Confirmed. 1.2.8.0 works for me also.

**Comment by ChrisAnd1998** [comment]
Thanks for letting me know 😁
